development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: toyapp123
  database: toy_app_development
  host: pgdb

test:
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: db/test.sqlite3

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: toyapp123
  database: toy_app_production
  host: pgdb